name: Update Docs

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - "R/**"
  pull_request:
    branches: [main, master]
    paths:
      - "R/**"

jobs:
  update-docs:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: roxygen2

      - name: Document
        run: Rscript -e 'roxygen2::roxygenise()'

      - name: Commit changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add man/\* NAMESPACE
          git commit -m 'Update docs' || echo "No modified docs."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
